# Generated by Django 2.2.5 on 2019-09-20 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Project Name')),
            ],
            options={
                'verbose_name': 'Photo Category',
                'verbose_name_plural': 'Photo Categories',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Project Name')),
                ('images', models.ImageField(blank=True, default='portfolio_imageDefault', upload_to='portfolio/images/')),
                ('description', models.TextField(blank=True, null=True)),
                ('ordering', models.IntegerField(blank=True, null=True)),
                ('link', models.URLField(blank=True, db_index=True, max_length=128, unique=True, verbose_name='Link')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.PhotoCategory')),
            ],
            options={
                'verbose_name': 'Photo',
                'verbose_name_plural': 'Photos',
                'ordering': ['ordering'],
            },
        ),
    ]
