# Generated by Django 2.2.5 on 2019-09-29 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20190921_0438'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['category', '-ordering'], 'verbose_name': 'Photo', 'verbose_name_plural': 'Photos'},
        ),
    ]
